fea_desafio:
  target: "{{ env_var('DBT_DEFAULT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DEV_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DEV_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DEV_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('DEV_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('DEV_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('DEV_SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('DEV_SNOWFLAKE_SCHEMA') }}"
      threads: 8
      client_session_keep_alive: False

